import Head from 'next/head';
import ClassList from '../components.js/ClassList';
import LoadingBar from '../components.js/LoadingBar';


export default function Classes() {
  return (
    <>
    <Head>
        <title>Classes | Fithub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_IMAGESPATH}/favicon.ico`} />
      </Head>
      <LoadingBar/>
    <ClassList/>
    </>
  )
}
