import Head from 'next/head'
import About from '../components/About';
import ClassList from '../components/ClassList';
import ContactContainer from '../components/ContactContainer';
import LoadingBar from '../components/LoadingBar';
import Plan from '../components/Plan';
import Header from '../components/Header'

export default function Home() {  

  return (
    <>
     <Head>
        <title>Fithub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_IMAGESPATH}/favicon.ico`} />
      </Head>
      <LoadingBar/>
<Header/>
    <ClassList/>
    <About/>
    <Plan/>
    <ContactContainer/>
    </>
  )
}
