import Head from 'next/head'
import React from 'react'
import LoadingBar from '../components/LoadingBar'
import Plan from '../components/Plan'
export default function PricePlan() {
  return (
    <>
     <Head>
        <title>Prices &amp; Plans | Fithub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_IMAGESPATH}/favicon.ico`} />
      </Head>
      <LoadingBar/>
   <Plan/>
    </>
  )
}
